# Generated by Django 5.2.8 on 2026-04-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_how_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='how',
            name='video',
        ),
    ]
