# Generated by Django 5.2.8 on 2026-04-10 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_how_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images'),
        ),
    ]
