# Generated by Django 5.2.8 on 2026-04-10 16:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_base_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='base',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images'),
        ),
    ]
