# Generated by Django 5.2.8 on 2026-04-10 16:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_base_avatar_alter_base_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
